### ISSUE TITLE
Multiple environments

### ISSUE THREAD

**Issue by mbessa** [jenkinsci/cerberus-testing-plugin#8]
Hello,

Is it possible to allow more than one environment in Jenkins plugin? 

Cerberus allow execution of campaigns using multiple environments, but currently if we set Jenkins plugin to execute for example, "_QA,UAT_", the url construction isn't properly done. Plugin render that value with URL encoding as "_&environment=QA%2CUAT_" and Cerberus API don't recognize it and return _"HTTP response : 500 Internal Server Error"_. It should parse that values as _"&environment=QA&environment=UAT"_ instead.

Thank you in advance
Marco

**Comment by nicodeur** [comment]
Hi,

Hi just add possibility to use multi environment separate by `,` (commit  5eea4885d3266308a2dcd4870322ffd1e2659fe0)

Available on next release

**Comment by mbessa** [comment]
Thank you Nicholas
